import { b as base64ToUint8Array } from '../virtual/_raw-helpers.mjs';

// ROLLUP_NO_REPLACE 
 const NewsletterSignup = base64ToUint8Array("PHNjcmlwdCBzZXR1cCBsYW5nPSJ0cyI+CiAgY29uc3QgY29sb3JzID0gewogICAgY2FyZDogIiNmZmZmZmYiLAogIH07Cjwvc2NyaXB0PgoKPHRlbXBsYXRlPgogIDxXcmFwcGVyPgogICAgPEVTZWN0aW9uIDpzdHlsZT0ieyBiYWNrZ3JvdW5kQ29sb3I6IGNvbG9ycy5jYXJkLCBwYWRkaW5nOiAnMzJweCcgfSI+CiAgICAgIDxFQ29udGFpbmVyPgogICAgICAgIDxFSGVhZGluZyBhcz0iaDEiPldlbGNvbWUgdG8gb3VyIG5ld3NsZXR0ZXIhPC9FSGVhZGluZz4KICAgICAgICA8RVRleHQ+VGhhbmsgeW91IGZvciBzaWduaW5nIHVwIGZvciB0aGUgc3VwYXN0YXJ0ZXIgbmV3c2xldHRlci48L0VUZXh0PgogICAgICA8L0VDb250YWluZXI+CiAgICA8L0VTZWN0aW9uPgogIDwvV3JhcHBlcj4KPC90ZW1wbGF0ZT4K");

export { NewsletterSignup as default };
//# sourceMappingURL=NewsletterSignup.mjs.map
