import { b as base64ToUint8Array } from '../virtual/_raw-helpers.mjs';

// ROLLUP_NO_REPLACE 
 const PrimaryButton = base64ToUint8Array("PHNjcmlwdCBzZXR1cCBsYW5nPSJ0cyI+CiAgY29uc3QgcHJvcHMgPSBkZWZpbmVQcm9wczx7CiAgICBocmVmOiBzdHJpbmc7CiAgfT4oKTsKCiAgZGVmaW5lT3B0aW9ucyh7CiAgICBpbmhlcml0QXR0cnM6IGZhbHNlLAogIH0pOwoKICBjb25zdCBjb2xvcnMgPSB7CiAgICBwcmltYXJ5OiAiIzEwYjk4MSIsCiAgICBwcmltYXJ5Rm9yZWdyb3VuZDogIiNmZmZmZmYiLAogIH07Cjwvc2NyaXB0PgoKPHRlbXBsYXRlPgogIDxFUm93PgogICAgPEVCdXR0b24KICAgICAgOmhyZWY9InByb3BzLmhyZWYiCiAgICAgIDpzdHlsZT0iewogICAgICAgIGJhY2tncm91bmRDb2xvcjogY29sb3JzLnByaW1hcnksCiAgICAgICAgY29sb3I6IGNvbG9ycy5wcmltYXJ5Rm9yZWdyb3VuZCwKICAgICAgICBib3JkZXJSYWRpdXM6ICcxMHB4JywKICAgICAgICBwYWRkaW5nTGVmdDogJzE2cHgnLAogICAgICAgIHBhZGRpbmdSaWdodDogJzE2cHgnLAogICAgICAgIHBhZGRpbmdUb3A6ICc4cHgnLAogICAgICAgIHBhZGRpbmdCb3R0b206ICc4cHgnLAogICAgICB9IgogICAgICB2LWJpbmQ9IiRhdHRycyIKICAgID4KICAgICAgPHNsb3QgLz4KICAgIDwvRUJ1dHRvbj4KICA8L0VSb3c+CjwvdGVtcGxhdGU+Cg==");

export { PrimaryButton as default };
//# sourceMappingURL=PrimaryButton.mjs.map
